export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';

export const SET_PLANNER_WEEK = 'SET_PLANNER_WEEK';
export const ADD_CALENDAR_DAY = 'ADD_CALENDAR_DAY';
export const REMOVE_CALENDAR_DAY = 'REMOVE_CALENDAR_DAY';
export const SET_PLANNER_EDIT_MODE = 'SET_PLANNER_EDIT_MODE';

export const SELECT = 'SELECT';

export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';

export const UPDATE_SEARCH_TYPE = 'UPDATE_SEARCH_TYPE';
export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';
